// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeK4tVzch9lTpyeC_-Fmp0L-5tDTDnWz4',
    appId: '1:706936262932:web:fc287f1d3d6f49f3b4f201',
    messagingSenderId: '706936262932',
    projectId: 'resume-builder-ef96e',
    authDomain: 'resume-builder-ef96e.firebaseapp.com',
    storageBucket: 'resume-builder-ef96e.firebasestorage.app',
    measurementId: 'G-HL3CRF7K2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMmFlCxONQkJYFD76kf1aeUChOlI9usLQ',
    appId: '1:706936262932:android:a8a516b53bcb871fb4f201',
    messagingSenderId: '706936262932',
    projectId: 'resume-builder-ef96e',
    storageBucket: 'resume-builder-ef96e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9xOl4tzMAtuLFBJU8b0oXf1KDwt10kY',
    appId: '1:706936262932:ios:8ceca6707e82c0b2b4f201',
    messagingSenderId: '706936262932',
    projectId: 'resume-builder-ef96e',
    storageBucket: 'resume-builder-ef96e.firebasestorage.app',
    iosBundleId: 'com.example.resume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn9xOl4tzMAtuLFBJU8b0oXf1KDwt10kY',
    appId: '1:706936262932:ios:8ceca6707e82c0b2b4f201',
    messagingSenderId: '706936262932',
    projectId: 'resume-builder-ef96e',
    storageBucket: 'resume-builder-ef96e.firebasestorage.app',
    iosBundleId: 'com.example.resume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeK4tVzch9lTpyeC_-Fmp0L-5tDTDnWz4',
    appId: '1:706936262932:web:94013d3eda899c7bb4f201',
    messagingSenderId: '706936262932',
    projectId: 'resume-builder-ef96e',
    authDomain: 'resume-builder-ef96e.firebaseapp.com',
    storageBucket: 'resume-builder-ef96e.firebasestorage.app',
    measurementId: 'G-LTGLZZ94EE',
  );
}
